[project]
name = "psbtc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ecdsa>=0.19.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
